### PR TITLE
Use linux platform if cygwin/gitbash detected

### LINKED ISSUE #7: Use linux platform if cygwin or Git Bash is detected
If the scripts are running via a linux-y shell on Windows, process.platform will still return 'win32'.

I'm submitting a PR with the fix.

Great library, thanks so much!

### PR DESCRIPTION
**Pull request by mathiscode**
Closes #7

### CODE REVIEW

**Comment by charlesguse** [comment]
Thanks for the PR and adding support for cygwin/gitbash!

**Comment by puengel** [comment]
Hello Guys,

Maybe someone else is dumb enough to run into this problem 😄 
If you open vs code from git bash `process.env.SHELL` will **always** evaluate to git bash even though you run node from vs codes' powershell or cmd terminal.

A short reminder for that might be useful in your documentation.

Cheers

**Comment by mathiscode** [comment]
Interesting find!

**Comment by mathiscode** [comment]
@puengel I submitted PR #19 so you can override the way run-script-os detects the platform to resolve this issue and #11

**Pull request merged**
